# setuptools import
from setuptools import setup, find_packages

setup(name="django-pyconfr",
      version="0.1",
      description="Pyconfr 2012 bundle first POC",
      long_description="""
      """,
      author="Florent Pigout",
      author_email="florent@toopy.org",
      url="http://github.com/pyconfr/django-pyconfr",
      install_requires = [
            "django",
            "south",
            "pinax",
            "pinax-theme-bootstrap",
            "django-debug-toolbar",
            "django-staticfiles",
            "django-uni-form",
            "django-email-confirmation",
            "django-timezones",
            "django-ajax-validation",
            "django-oauth-access",
            "pytz",
            "django-openid",
            "python-openid",
            "oauth2",
            "biblion",
            "creole",
            "Pygments",
            "docutils",
            "django-wakawaka",
            "django-markitup",
            "django-fixture-generator",
            "nashvegas",
            "redis",
            "sorl-thumbnail",
            "icalendar",
            "PIL",
            "gondor",
            "mailout",
            "markdown",
            "html5lib",
            "django-reversion",
            "django-compressor",
            "django-mailer",
            "django-analytics",
            "gunicorn"
      ],
      packages = find_packages('src'),
      package_dir = {'': 'src'},
      include_package_data=True,
      zip_safe=False,
      classifiers = ["Development Status :: 4 - Beta",
                     "Environment :: Web Environment",
                     "Framework :: Django",
                     "Intended Audience :: Developers",
                     "License :: OSI Approved :: MIT License",
                     "Operating System :: OS Independent",
                     "Programming Language :: Python",
                     "Topic :: Utilities"],
      )
